# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

#- task: FortifyOnDemandStatic@9
#  inputs:
#    FortifyProjects: '$(Pipeline.Workspace)/s'
#    FodConnection: 'FoD_AMS_API'
#    ReleaseOptions: '0'
#    ReleaseId: 1233871
#    EntitlementSelection: '1'
#    EntitlementPreference: '1'
#    OverrideScanSettings: '2'
#    InProgressScanActionType: '1'
#    RemediationScanPreference: '2'
#    BuildType: 'mvn'
#    PolicyFailAction: '0'
#    PollingInterval: 0

#- task: FortifyOnDemandStatic@9
#  inputs:
#    FortifyProjects: '$(Pipeline.Workspace)/s'
#    FodConnection: 'FoD_AMS_API'
#    ReleaseOptions: '2'
#    ApplicationName: 'QS 1902008 - Take 2'
#    BusinessCriticality: '1'
#    ReleaseName: '2 is better than 1'
#    Owner: 12665
#    EntitlementSelection: '1'
#    EntitlementPreference: '1'
#    OverrideScanSettings: '1'
#    AssessmentTypeId: '274'
#    InProgressScanActionType: '2'
#    RemediationScanPreference: '2'
#    BuildType: 'none'
#    PolicyFailAction: '0'

- task: FortifyOnDemandStatic@9
  inputs:
    FortifyProjects: '$(Pipeline.Workspace)/s'
    FodConnection: 'FoD_AMS_API'
    ReleaseOptions: '2'
    ApplicationName: 'QS 1902008 - Take 3'
    BusinessCriticality: '1'
    ReleaseName: '1'
    Owner: 12665
    EntitlementSelection: '0'
    Entitlement: 14154
    EntitlementPreference: '1'
    OverrideScanSettings: '1'
    AssessmentTypeId: '274'
    InProgressScanActionType: '2'
    RemediationScanPreference: '2'
    BuildType: 'none'
    PolicyFailAction: '0'